nome = input('Escreva seu nome:')
idade = input('Escreva sua idade:')
tipo_nome = type(nome)
tipo_idade = type(idade)
altura = input('Escreva sua altura:')
print(nome, 'tem', idade, "anos", 'e', altura , 'de altura.')